Traduction `mutations.md`
vuejs-fr/vuex pull request #11
Opened 2017-05-20 09:43 UTC by Haeresis

À priori le nombre de ligne à changé. Il doit y avoir du nouveau par ici :)

2017-05-20 10:16 UTC, Kocal requested changes
C'est tout pour moi !

2017-05-20 10:16 UTC, Kocal commented on docs/en/mutations.md
> +La seule façon de vraiment modifier le state dans un store Vuex est de commiter une mutation. Les mutations Vuex sont très similaires aux events : chaque mutation a un **type** sous forme de chaîne d
> modifier l'état

> est d'acter 

> reçoit l'état

2017-05-20 10:16 UTC, Kocal commented on docs/en/mutations.md
> +Vous ne pouvez pas appeler directement un handler de mutation. La façon de faire est plutôt comme un abonnement à un event : "Lorsqu'une mutation du type `increment` est déclenchée, appelle ce handle
> à un événement

2017-05-20 10:16 UTC, Kocal commented on docs/en/mutations.md
> +Une méthode alternative pour commiter une mutation est d'utiliser directement un objet qui a une propriété `type` :
> pour acter

2017-05-20 10:16 UTC, Kocal commented on docs/en/mutations.md
> +Puisqu'un state de store de Vuex est rendu réactif par Vue, lorsque nous mutons le state, les composants Vue observant ce state seront automatiquement mis à jour. Cela signifie également que les muta
> Puisqu'un état de

> observant cet état

2017-05-20 10:16 UTC, Kocal commented on docs/en/mutations.md
> +1. Initialisez de préférence le state initial de votre state avec tous les champs désirés auparavant.
> l'état initial de votre état

2017-05-20 10:16 UTC, Kocal commented on docs/en/mutations.md
> +### commiter des mutations dans les composants
> ### Acter

2017-05-20 10:16 UTC, Kocal commented on docs/en/mutations.md
> +### commiter avec un Payload
> ### Acter

2017-05-20 10:16 UTC, Kocal commented on docs/en/mutations.md
> +Maintenant imaginons que nous debuggons l'application et que nous regardons dans les logs de mutation des devtools. Pour chaque mutation enregistrée, le devtool aura besoin de capturer un instantané
> lorsque la mutation est actée

2017-05-20 10:16 UTC, Kocal commented on docs/en/mutations.md
> +Vous pouvez commiter des mutations dans les composants avec `this.$store.commit('xxx')`, ou en utilisant le helper `mapMutations` qui attache les méthodes du composant aux appels de `store.commit` (n
> Vous pouvez acter

2017-05-20 10:16 UTC, Kocal commented on docs/en/mutations.md
> +      'increment' // map this.increment() to this.$store.commit('increment')
> map this.increment() à this.$store.commit('increment)

2017-05-20 10:16 UTC, Kocal commented on docs/en/mutations.md
> -      'incrementBy' // this.incrementBy(amount) maps to this.$store.commit('incrementBy', amount)
Cette partie a disparu.

2017-05-20 10:16 UTC, Kocal commented on docs/en/mutations.md
>        add: 'increment' // map this.add() to this.$store.commit('increment')
> map this.add() à this.$store.commit('increment')

2017-05-20 10:16 UTC, Kocal commented on docs/en/mutations.md
> +L'asynchronisme combiné à la mutation du state peut rendre votre programme très difficile à comprendre. Par exemple, lorsque vous appelez deux méthodes avec toutes les deux des callbacks asynchrones
> la mutation de l'état

> qui changent l'état

2017-05-20 10:21 UTC, MachinisteWeb reviewed
Un peu de travail de ce côté et une petite reflexion sur le terme « linters » est a envisagé

2017-05-20 10:21 UTC, MachinisteWeb commented on docs/en/mutations.md
> +La seule façon de vraiment modifier le state dans un store Vuex est de commiter une mutation. Les mutations Vuex sont très similaires aux events : chaque mutation a un **type** sous forme de chaîne d
> modifier l'état

> est d'acter

> aux évènements

> et un **gestionnaire**

> La fonction de gestion est en charge de procéder aux véritables modifications de l'état

2017-05-20 10:21 UTC, MachinisteWeb commented on docs/en/mutations.md
>  })
À traduire

> muter l'état

2017-05-20 10:21 UTC, MachinisteWeb commented on docs/en/mutations.md
> +Vous ne pouvez pas appeler directement un handler de mutation. La façon de faire est plutôt comme un abonnement à un event : "Lorsqu'une mutation du type `increment` est déclenchée, appelle ce handle
> un gestionnaire de mutation.

> Le partie pris ici est similaire à l'abonnement à un évènement : « ... ce gestionnaire. »

> un gestionnaire de mutation

> appeler `store.commit`

2017-05-20 10:21 UTC, MachinisteWeb commented on docs/en/mutations.md
> +### commiter avec un Payload
> Acter avec un argument additionnel

2017-05-20 10:21 UTC, MachinisteWeb commented on docs/en/mutations.md
> +Vous pouvez donner un autre argument à **store.commit** pour la mutation, qui s'appelle **payload** :
> Vous pouvez donner un argument additionnel (« payload ») à la fonction `store.commit` lors de la mutation :

2017-05-20 10:21 UTC, MachinisteWeb commented on docs/en/mutations.md
> +Dans la plupart des cas, le payload devrait être un objet, ainsi il peut contenir plusieurs champs, et les mutations enregistrées seront également plus descriptives :
> l'argument additionnel

2017-05-20 10:21 UTC, MachinisteWeb commented on docs/en/mutations.md
>  ### Object-Style Commit
> Acter avec un objet

2017-05-20 10:21 UTC, MachinisteWeb commented on docs/en/mutations.md
> +Une méthode alternative pour commiter une mutation est d'utiliser directement un objet qui a une propriété `type` :
> pour acter une mutation

2017-05-20 10:21 UTC, Haeresis commented on docs/en/mutations.md
> +Lors de l'utlisation de l'object-style commit, l'objet entier sera fourni comme payload aux handlers de mutation, donc le handler reste inchangé :
> Lors de l'utilisation d'un objet pour acter, c'est l'objet lui-même qui ferra office d'argument pour le gestionnaire de mutation, le gestionnaire reste donc inchangé :

2017-05-20 10:21 UTC, Haeresis commented on docs/en/mutations.md
> +Puisqu'un state de store de Vuex est rendu réactif par Vue, lorsque nous mutons le state, les composants Vue observant ce state seront automatiquement mis à jour. Cela signifie également que les muta
> un état de store

> mutons l'état

> cet état

> sujettes aux mêmes limitations qu'avec l'utilisation de Vue seul.

2017-05-20 10:21 UTC, Haeresis commented on docs/en/mutations.md
> +1. Initialisez de préférence le state initial de votre state avec tous les champs désirés auparavant.
> de préférence le store initial

> de votre état

2017-05-20 10:21 UTC, Haeresis commented on docs/en/mutations.md
> +2. Lorsque vous ajoutez de nouvelles propriétés à un Object, vous devriez soit :
> `Object`

2017-05-20 10:21 UTC, Haeresis commented on docs/en/mutations.md
> +  - Utiliser `Vue.set(obj, 'newProp', 123)`, ou -
> ou

2017-05-20 10:21 UTC, Haeresis commented on docs/en/mutations.md
> +  - Remplacer cet Object par un nouvel Object. Par exemple, en utilisant [object spread syntax](https://github.com/sebmarkbage/ecmascript-rest-spread) (stage-2), il est possible d'écrire :
> `Object` par un nouvel `Object`

2017-05-20 10:21 UTC, Haeresis commented on docs/en/mutations.md
> +  - Remplacer cet Object par un nouvel Object. Par exemple, en utilisant [object spread syntax](https://github.com/sebmarkbage/ecmascript-rest-spread) (stage-2), il est possible d'écrire :
> l'opérateur de décomposition

2017-05-20 10:21 UTC, Haeresis commented on docs/en/mutations.md
>  })
À traduire

2017-05-20 10:21 UTC, Haeresis commented on docs/en/mutations.md
> +C'est une façon de faire régulière que d'utiliser des constantes pour les types de mutations dans diverses implémentations de Flux. Cela permet au code de bénéficier d'outils comme les linters, et éc
linter ? Une idée pour la traduction ?

Je crois qu'on l'avais déjà rencontré dans la doc officiel et on a mis « support de code » ou un truc comme ça

2017-05-20 10:21 UTC, Haeresis commented on docs/en/mutations.md
> +Utiliser les constantes ou non relève de la préférence personnelle &mdash; cela peut être bénéfique sur un gros projet avec beaucoup de développeurs, mais c'est totalement optionnel si vous n'aimez p
> personnelle. Cela

2017-05-20 10:21 UTC, Haeresis commented on docs/en/mutations.md
> +Une règle importante à retenir est que **les fonctions handler de mutations doivent être synchrones**. Pourquoi ? Considérons l'exemple suivant :
> les gestionnaires de mutation

2017-05-20 10:21 UTC, Haeresis commented on docs/en/mutations.md
> +Maintenant imaginons que nous debuggons l'application et que nous regardons dans les logs de mutation des devtools. Pour chaque mutation enregistrée, le devtool aura besoin de capturer un instantané
> deboguons

> des outils de développement (« devtools »)

> « avant »

> « après »

> la fonction de rappel asynchrone

> la fonction de rappel n'est pas encore

> la mutation est actée

> quand la fonction de rappel

> appelé. Toute mutation de l'état effectuée dans une fonction de retour asynchrone

2017-05-20 10:21 UTC, Haeresis commented on docs/en/mutations.md
> +### commiter des mutations dans les composants
> ### Acter

2017-05-20 10:21 UTC, Haeresis commented on docs/en/mutations.md
> +Vous pouvez commiter des mutations dans les composants avec `this.$store.commit('xxx')`, ou en utilisant le helper `mapMutations` qui attache les méthodes du composant aux appels de `store.commit` (n
> pouvez acter

> la fonction utilitaire `mapMutations`

2017-05-20 10:21 UTC, Haeresis commented on docs/en/mutations.md
>  }
À traduire

2017-05-20 10:21 UTC, Haeresis commented on docs/en/mutations.md
> +L'asynchronisme combiné à la mutation du state peut rendre votre programme très difficile à comprendre. Par exemple, lorsque vous appelez deux méthodes avec toutes les deux des callbacks asynchrones
> de l'état

> fonctions de rappel asynchrones qui change l'état

> fonction de rappel est appelé en première ?

2017-05-22 12:11 UTC, Haeresis commented on docs/en/mutations.md
>  // should be done at this moment.
À traduire

2017-05-22 12:12 UTC, Haeresis commented
Si c'est bon pour toi @Kocal, on merge. Je vais faire une PR en pour remettre les ticks dans l'original.

2017-05-22 12:27 UTC, Kocal approved these changes

2017-05-22 12:28 UTC, Kocal commented on docs/en/mutations.md
> -      'incrementBy' // this.incrementBy(amount) maps to this.$store.commit('incrementBy', amount)
Rajoutée dans 102eb492c9f5e1479473e6e5b6fdd6d5d7aad740.

2017-05-22 12:28 UTC, Kocal commented
Ok pour moi :)

2017-05-22 13:03 UTC, merged