Traduction de `actions.md`
vuejs-fr/vuex pull request #12
Opened 2017-05-22 13:02 UTC by Haeresis

C'est parti pour de l'action !

2017-05-22 13:33 UTC, Haeresis commented on docs/en/actions.md
> +- Au lieu de modifier le state, les actions committent des mutations.
> modifier l'état

> actent des

2017-05-22 13:33 UTC, Haeresis commented on docs/en/actions.md
> +Les handlers d'action reçoivent un objet contexte qui expose le même set de méthodes/propriétés que l'instance du store, donc vous pouvez appeler `context.commit` pour commiter une mutation, ou accéd
> les gestionnaires d'action

> les mêmes méthodes/propriétés

> acter une mutation

> accéder à l'état et aux accesseurs

> modules.md

2017-05-22 13:33 UTC, Haeresis commented on docs/en/actions.md
> +### Dispatcher des actions dans les composants
> Propager des

2017-05-22 13:33 UTC, Haeresis commented on docs/en/actions.md
> +Les actions prennent en charge le même format de payload et *object-style dispatch* :
> également en charge les paramètres additionnels (« payload ») et les objets pour propager :

2017-05-22 13:33 UTC, Haeresis commented on docs/en/actions.md
> +// dispatcher avec un payload
propager avec un paramètre additionnel

2017-05-22 13:33 UTC, Haeresis commented on docs/en/actions.md
> +// dispatcher avec un object
propager avec un objet

2017-05-22 13:33 UTC, Haeresis commented on docs/en/actions.md
> +Un exemple plus pratique d'une application du monde réel serait une action pour check-out un panier d'achats, ce qui implique **d'appeler une API asynchrone** et de **comitter de multiples mutations*
> Un exemple concret d'application serait

> pour vider un panier d'achats

> acter de multiples

2017-05-22 13:33 UTC, Haeresis commented on docs/en/actions.md
> +    // l'API du shop prend un callback success et un callback failure
// l'API de la boutique en ligne prend une fonction de rappel en cas de succès et une en cas d'échec

2017-05-22 13:33 UTC, Haeresis commented on docs/en/actions.md
>        // handle success
> gérer le succès

> gérer l'échec

2017-05-22 13:33 UTC, Haeresis commented on docs/en/actions.md
> +Notez que nous procédons à un flux d'opérations asynchrones, et enregistrons les effets de bord (mutation du state) de l'action en les committant.
> mutation de l'état

> les actants

2017-05-22 13:33 UTC, Haeresis commented on docs/en/actions.md
> +### Dispatcher des actions dans les composants
> Propager

2017-05-22 13:33 UTC, Haeresis commented on docs/en/actions.md
> +Vous pouvez dispatcher des actions dans les composants avec `this.$store.dispatch('xxx')`, ou en utilisant le helper `mapActions` qui attache les méthodes du composant aux appels de `store.dispatch`
> pouvez propager

> la fonction utilitaire

2017-05-22 13:33 UTC, Haeresis commented on docs/en/actions.md
> +La première chose à savoir est que `store.dispatch` retourne la valeur retournée par le handler de l'action déclenchée, vous pouvez donc retourner une Promise :
> peut gérer la Promesse (« Promise ») retournée par le gestionnaire d'action déclenché et par conséquent vous pouvez également retourner une Promesse :

2017-05-22 13:33 UTC, Haeresis commented on docs/en/actions.md
> +Pour finir, nous pouvons utiliser de [async / await](https://tc39.github.io/ecmascript-asyncawait/), une fonctionnalité JavaScript qui sera disponible très bientôt, nous pouvons composer nos actions
> en utilisant [`async` / `await`]

2017-05-22 13:33 UTC, Haeresis commented on docs/en/actions.md
> +// sachant que getData() et getOtherData() retournent des Promises
> `getData()` et `getOtherData()`

> Promesses

2017-05-22 13:33 UTC, Haeresis commented on docs/en/actions.md
>  }
// attendre que `actionA` soit finie

2017-05-22 13:33 UTC, Haeresis commented on docs/en/actions.md
> +> Il est possible pour un `store.dispatch` de déclencher plusieurs handlers d'action dans différents modules. Dans ce genre de cas, la valeur retournée sera une Promise qui se résoud quand tous les h
> gestionnaires d'action

> une Promesse

> gestionnaires déclenchés

2017-05-22 15:51 UTC, Kocal requested changes

2017-05-22 15:51 UTC, Kocal commented on docs/en/actions.md
> +Les handlers d'action reçoivent un objet contexte qui expose le même set de méthodes/propriétés que l'instance du store, donc vous pouvez appeler `context.commit` pour commiter une mutation, ou accéd
> expose le même ensemble de méthodes/propriétés

> elle-même, lorsque

2017-05-22 15:51 UTC, Kocal commented on docs/en/actions.md
> +Notez que nous procédons à un flux d'opérations asynchrones, et enregistrons les effets de bord (mutation du state) de l'action en les committant.
> les actant

2017-05-23 08:01 UTC, Haeresis commented
Merci pour tes retours @Kocal, c'est dans la boite !

2017-05-23 09:19 UTC, Kocal approved these changes

2017-05-23 09:22 UTC, merged