Traduction de `modules.md`
vuejs-fr/vuex pull request #13
Opened 2017-05-22 13:45 UTC by Haeresis

Et en avant pour les modules, je vois qu'il y a des pends de texte nouveau !

2017-05-22 14:45 UTC, MachinisteWeb commented on docs/en/modules.md
> +Parce qu'il utilise un _single state tree_, tout le state de notre application est contenu dans un seul et même gros objet. Cependant, au fur et à mesure que notre application grandit, le store peut
> Du fait de l'utilisation d'un arbre d'état unique, tout l'état

2017-05-22 14:45 UTC, MachinisteWeb commented on docs/en/modules.md
> +Pour y remédier, Vuex nous permet de diviser notre store en **modules**. Chaque module peut contenir son propre state, mutations, actions, getters, et même d'autres modules.
> ses propres état, mutations, actions, accesseurs, et même contenir ses propres modules internes.

2017-05-22 14:45 UTC, MachinisteWeb commented on docs/en/modules.md
> +store.state.a // -> le state du module A
> l'état du `moduleA`
> l'état du `moduleB`

2017-05-22 14:45 UTC, MachinisteWeb commented on docs/en/modules.md
> +### State local d'un module
> État local d'un module

2017-05-22 14:45 UTC, MachinisteWeb commented on docs/en/modules.md
> +Dans les mutations et getters d'un module, le premier argument reçu sera le **state local du module**.
> accesseurs

> l'état local du module

2017-05-22 14:45 UTC, MachinisteWeb commented on docs/en/modules.md
> +      // state est le state du module local
> `state` est l'état du module local

2017-05-22 14:45 UTC, MachinisteWeb commented on docs/en/modules.md
> +De façon similaire, dans les actions du module, `context.state` exposera le state local, et le state racine sera disponible avec `context.rootState` :
> l'état local, et l'état racine

2017-05-22 14:45 UTC, MachinisteWeb commented on docs/en/modules.md
> +Également, dans les getters du module, le state racine sera exposé en troisième argument :
> accesseurs

> l'état racine

2017-05-22 14:45 UTC, Haeresis commented
J'ai traduit sur le tas @Kocal alors je te laisse revoir ma traduction en même temps !

2017-05-22 16:12 UTC, Kocal requested changes
C'est tout pour moi !

2017-05-22 16:12 UTC, Kocal commented on docs/en/modules.md
> +Par défaut, les actions, mutations et accesseurs à l'intérieur d'un module son toujours enregistré sous l'**espace de nom global**. Cela permet a de multiple module d'être réactif au même type de mut
> enregistrés

> à de multiples modules d'être réactifs

2017-05-22 16:12 UTC, Kocal commented on docs/en/modules.md
> +Si vous souhaitez que votre module soit auto-suffisant et réutilisable, vous pouvez le ranger sous un espace de nom avec `namespaced: true`. Quand le module est enregistré, tous ses accesseurs, actio
> basés

2017-05-22 16:12 UTC, Kocal commented on docs/en/modules.md
> +Les accesseurs et actions sous espace de nom reçoivent des `getters`, `dispatch` et `commit` localisé. En d'autres termes, vous pouvez utiliser les paramètres de module sans écrire de prefix dans le
> localisés.

> dans ce même

> espace de nom ou non, n'affecte

2017-05-22 16:12 UTC, Kocal commented on docs/en/modules.md
> +Si vous voulez utiliser des état et accesseurs globaux, `rootState` et `rootGetters` sont passés en 3ième et 4ième arguments des fonctions accès et sont également exposés en tant que propriété de l'o
> des états

> fonctions d'accès

2017-05-22 16:12 UTC, Kocal commented on docs/en/modules.md
> +      // Les `getters` sont localisé dans le module des accesseurs
> sont localiés

2017-05-22 16:12 UTC, Kocal commented on docs/en/modules.md
> +L'état des modules seront disponibles dans `store.state.myModule` et `store.state.nested.myModule`.
> est disponible

2017-05-22 16:12 UTC, Kocal commented on docs/en/modules.md
> +Parfois nous devrons créer de multiples instances d'un module pour par exemple :
> d'un module, par exemple

2017-05-23 08:20 UTC, Haeresis commented
Merci @Kocal pour ta review de review ! :) C'est ajouté !

2017-05-23 09:19 UTC, Kocal approved these changes

2017-05-23 09:22 UTC, merged