Review de `plugins.md`
vuejs-fr/vuex pull request #14
Opened 2017-05-22 14:51 UTC by Haeresis

Celui là n'a pas de nouvelle lignes

2017-05-22 15:00 UTC, Haeresis commented on docs/en/plugins.md
>  }
À traduire

2017-05-22 15:00 UTC, Haeresis commented on docs/en/plugins.md
> +### Commiter des mutations dans des plugins
> Acter

2017-05-22 15:00 UTC, Haeresis commented on docs/en/plugins.md
> +Les plugins ne sont pas autorisés à muter directement le state &mdash; tout comme vos composants, ils peuvent simplement déclencher des changements en committant des mutations.
> l'état. Tout

> en actant des

2017-05-22 15:00 UTC, Haeresis commented on docs/en/plugins.md
> +En commitant des mutations, un plugin peut être utilisé pour synchroniser la source de données avec le store. Par exemple, pour synchroniser la source de données d'un websocket vers le store (c'est j
> En actant des

>une websocket

2017-05-22 15:00 UTC, Haeresis commented on docs/en/plugins.md
> +### Prendre des instantanés du state
> de l'état

2017-05-22 15:00 UTC, Haeresis commented on docs/en/plugins.md
> +Parfois un plugin peut vouloir reçevoir des "instantanés" du state, et également comparer le state post-mutation avec le state pre-mutation. Pour faire ceci, vous aurez besoin d'effectuer une deep-co
> « instantanés »

2017-05-22 15:00 UTC, Haeresis commented on docs/en/plugins.md
> +Parfois un plugin peut vouloir reçevoir des "instantanés" du state, et également comparer le state post-mutation avec le state pre-mutation. Pour faire ceci, vous aurez besoin d'effectuer une deep-co
> l'état post-mutation avec l'état pre-mutation.

> copie profonde / copie complète de l'état

2017-05-22 15:00 UTC, Haeresis commented on docs/en/plugins.md
> +**Les plugins qui peuvent prendre des instantanés ne devraient être utilisés que pendant le développement.** Lorsqu'on utilise Webpack ou Browserify, on peut laisser nos devtools s'occuper de ça pour
> webpack

> outils de développement (« devtools »)

2017-05-22 15:00 UTC, Haeresis commented on docs/en/plugins.md
> +Le plugin sera utilisé par défaut. Pour la production, vous aurez besoin de [DefinePlugin](https://webpack.github.io/docs/list-of-plugins.html#defineplugin) pour Webpack ou de [envify](https://github
> webpack

2017-05-22 15:00 UTC, Haeresis commented on docs/en/plugins.md
> +### Plugin logger intégré
> Plugin de logs intégré

2017-05-22 15:00 UTC, Haeresis commented on docs/en/plugins.md
> +Vuex fournit un plugin de logger à des fins de debugging :
> plugin de logs

> débogage

2017-05-22 15:00 UTC, Haeresis commented on docs/en/plugins.md
>  })
À traduire

2017-05-22 15:00 UTC, Haeresis commented on docs/en/plugins.md
> +Le fichier logger peut aussi être inclus directement via une balise `script`, et exposera la fonction `createVuexLogger` globalement.
> Le fichier de logs

2017-05-22 15:00 UTC, Haeresis commented on docs/en/plugins.md
> +Notez que le plugin logger peut prendre des instantanés du state, ne l'utilisez donc que durant le développement.
> plugin de logs

> de l'état

2017-05-22 16:16 UTC, Kocal reviewed
Pas grand chose à corriger dans la traduction

2017-05-22 16:16 UTC, Kocal commented on docs/en/plugins.md
> +Parfois un plugin peut vouloir reçevoir des "instantanés" du state, et également comparer le state post-mutation avec le state pre-mutation. Pour faire ceci, vous aurez besoin d'effectuer une deep-co
> recevoir

2017-05-22 16:17 UTC, Kocal requested changes
(me suis encore trompé)

2017-05-23 08:43 UTC, Haeresis commented
J'ai traduis quelques commentaires (je te laisse jetter un oeil). Dès que c'est bon pour toi je merge.

2017-05-23 09:21 UTC, Kocal approved these changes

2017-05-23 09:23 UTC, merged