Relecture de strict.md
vuejs-fr/vuex pull request #15
Opened 2017-06-17 10:10 UTC by Haeresis

2017-06-28 07:31 UTC, Haeresis commented
Dispo pour cette relecture @Kocal ? Plus que ses 2 fichiers et notre travail sur Vuex sera bouclé pour la relecture global !

2017-06-28 09:14 UTC, Kocal requested changes
Merci pour tes 2 traductions, 2/3 petites modifications à apporter. ^^

2017-06-28 09:14 UTC, Kocal commented on docs/en/strict.md
> +Pour activer le mode strict, passez simplement l'option `strict: true` lorsque vous créez un store Vuex :
> pendant la création d'un store Vuex

2017-06-28 09:14 UTC, Kocal commented on docs/en/strict.md
> +### Développement vs. production
> Production

Je pense que tu as du faire exprès d'écrire `production`, mais je pense qu'il faudrait mieux garder `Production`.

2017-06-29 07:15 UTC, Haeresis commented on docs/en/strict.md
> +### Développement vs. production
Je comprends, mais il ressemble à la structure « Titre ou sous-titre » et cette structure ne prend pas de majuscule autre que à la première lettre. Pour rester cohérent avec les autres titrage, je vais laisser comme ça. Je dis pas que j'ai fondamentalement raison hein, je dis juste que je fais ce choix !

2017-06-29 07:15 UTC, Haeresis commented
Merci @Kocal pour cette autre review. On dirait qu'on a achevé une traduction !!! (Même si celle là n'était qu'une relecture haha).

Merge si c'est ok pour toi !

2017-06-29 09:56 UTC, merged