Relecture de `forms.md`
vuejs-fr/vuex pull request #16
Opened 2017-06-17 10:31 UTC by Haeresis

L'un des dernier fichier avant d'avoir la traduction de la doc Vuex complètement monitoré :)

2017-06-20 06:43 UTC, Kocal requested changes
Une petite erreur

2017-06-20 06:43 UTC, Kocal commented on docs/en/forms.md
> +La Vuex peut gérer ça en liant la valeur de l'`input` et en appelant une action sur l'évènement `input` ou `change` :
> La « façon Vuex » pour gérer cela est de lier

2017-06-22 08:14 UTC, Haeresis commented
Merci @Kocal ! J'ai utilisé « la méthode Vuex » en référence à « la méthode ... » couramment utilisé en français. « La façon X » ne me semble pas quelque chose de naturellement français.

2017-06-22 13:22 UTC, Kocal commented
Oui c'est pas faux, peut-être que je traduis « ...'s way » trop littéralement. 🤔

2017-06-22 13:55 UTC, Haeresis commented
Oui tu peux, sourtout valide la PR :)

2017-06-23 06:34 UTC, Kocal approved these changes

2017-06-23 06:34 UTC, merged