Relecture de `testing.md`
vuejs-fr/vuex pull request #17
Opened 2017-06-17 13:10 UTC by Haeresis

Une autre relecture

2017-06-20 06:40 UTC, Kocal requested changes
Quelques petites erreurs 😱

2017-06-20 06:40 UTC, Kocal commented on docs/en/testing.md
> +Exemple de test de mutation utilisant Mocha + Chai (vous pouvez utiliser n'importe quel framework/bibliothèque d'assertion selon votre préférence) :
> selon vos préférences

2017-06-20 06:40 UTC, Kocal commented on docs/en/testing.md
> +// étulisation de la syntaxe `require` pour les loaders.
> utilisation

2017-06-20 06:40 UTC, Kocal commented on docs/en/testing.md
> +// avec inject-loader, cela retourne un module le fabrique
> un module de fabrique

2017-06-22 07:19 UTC, Haeresis commented
Merci @Kocal. J'ai remonté tes points !

Si c'est bon pour toi tu peux merger.

2017-06-22 13:20 UTC, Kocal approved these changes

2017-06-22 13:21 UTC, merged

2017-06-22 13:21 UTC, Kocal commented
Approuvé, mergé, et branche supprimée !