Relecture de `api.md`
vuejs-fr/vuex pull request #19
Opened 2017-06-17 13:56 UTC by Haeresis

Dernier fichier à mettre à jour.

2017-06-28 07:30 UTC, Haeresis commented
Dispo pour cette relecture @Kocal ? Plus que ses 3 fichiers et notre travail sur Vuex sera bouclé pour la relecture global !

2017-06-28 09:10 UTC, Kocal requested changes
Pas grand chose à review :)

2017-06-28 09:10 UTC, Kocal commented on docs/en/api.md
> +    L'objet état racine pour le store Vuex.
> d'état racine

2017-06-28 09:10 UTC, Kocal commented on docs/en/api.md
> +    Spécifiquement quand défini dans un module
> Arguments spécifiques quand ..

2017-06-28 09:10 UTC, Kocal commented on docs/en/api.md
> +    Spécifiquement quand défini dans un module
> Arguments spécifiques quand ...

Me parait plus français.

2017-06-28 09:10 UTC, Kocal commented on docs/en/api.md
> +    Les getters enregistrés sont exposés sur `store.getters`.
> Les accesseurs

2017-06-28 09:10 UTC, Kocal commented on docs/en/api.md
> +  Remplacer l'état racine du store. Utiliser seulement pour hydrater l'état ou voir l'état dans le temps.
> ou dans le but de voyager dans le temps.

Car les voyages dans le temps c'est trop cool (fan de Doctor Who) :)

2017-06-28 09:10 UTC, Kocal commented on docs/en/api.md
> +  Observer de façon réactive la valeur de retour d'une fonction accesseur, et appeler la fonction de rappel lorsque la valeur change. L'accesseur reçoit l'état du store comme unique argument. Accepte
> Accepte un objet optionnel d'options

2017-06-29 07:05 UTC, Haeresis commented
Merci @Kocal ! Si c'est bon pour toi... merge !

2017-06-29 09:57 UTC, Kocal approved these changes

2017-06-29 09:57 UTC, merged