Relecture `state.md`
vuejs-fr/vuex pull request #8
Opened 2017-05-18 15:43 UTC by Haeresis

Relecture du fichier state.md

2017-05-18 16:01 UTC, Kocal requested changes
Merci pour la PR ~

Quelques remarques notamment sur la traduction de `state` et de `store`. Je ne sais plus si on s'était mis d'accord sur une traduction FR de ces termes-là ou non.

D'ailleurs, ça serait bien de les rajouter ici https://github.com/vuejs-fr/vuejs.org/issues/4

2017-05-18 16:01 UTC, Kocal commented on docs/en/state.md
> +Vuex utilise un **single state tree** &mdash; cet unique objet contient tout le state au niveau applicatif et sert de "source unique de vérité". Cela signifie également que vous n'aurez qu'un seul st
> contient tout l'état

> vous n'aurez qu'un seul gestionnaire d'état

> une partie d'état spécifique

> des instantanés de l'état actuel

2017-05-18 16:01 UTC, Kocal commented on docs/en/state.md
> +Le _single state tree_ n'entre pas en conflit avec la modularité &mdash; dans les prochains chapitres, nous examinerons comment séparer votre state et vos mutations dans des sous-modules.
> votre état

2017-05-18 16:01 UTC, Kocal commented on docs/en/state.md
> +### Récupérer le state Vuex dans des composants Vue
> ### Récupérer l'état

2017-05-18 16:01 UTC, Kocal commented on docs/en/state.md
> +Alors, comment affichons-nous le state du store dans nos composants Vue ? Puisque les stores Vuex sont réactifs, la façon la plus simple d'y "récupérer" le state est de simplement retourner une parti
state/store

2017-05-18 16:01 UTC, Kocal commented on docs/en/state.md
> +En fournissant l'option `store` à l'instance racine, le store sera injecté dans tous les composants enfants de la racine et sera disponible sur ceux-ci avec `this.$store`. Mettons à jours notre implé
> sur ces derniers

> Mettons à jour

2017-05-18 16:38 UTC, MachinisteWeb commented on docs/en/state.md
>  ### Single State Tree
> Arbre d'état unique

2017-05-18 16:38 UTC, MachinisteWeb commented on docs/en/state.md
> +Vuex utilise un **single state tree** &mdash; cet unique objet contient tout le state au niveau applicatif et sert de "source unique de vérité". Cela signifie également que vous n'aurez qu'un seul st
> Vuex utilise un **arbre d'état unique**, c'est-à-dire que

> tout l'état

> « source de vérité unique »

> Un arbre d'état unique rend la localisation d'une partie spécifique de l'état rapide et permet

> de l'état

> débogage

2017-05-18 16:38 UTC, MachinisteWeb commented on docs/en/state.md
> +Le _single state tree_ n'entre pas en conflit avec la modularité &mdash; dans les prochains chapitres, nous examinerons comment séparer votre state et vos mutations dans des sous-modules.
> L'arbre d'état unique

> modularité. Dans

> votre état et vos mutations

2017-05-18 16:38 UTC, MachinisteWeb commented on docs/en/state.md
> +### Récupérer le state Vuex dans des composants Vue
> ### Récupération d'état Vuex dans des composants Vue

2017-05-18 16:38 UTC, MachinisteWeb commented on docs/en/state.md
> +Alors, comment affichons-nous le state du store dans nos composants Vue ? Puisque les stores Vuex sont réactifs, la façon la plus simple d'y "récupérer" le state est de simplement retourner une parti
> l'état du store

> « récupérer » l'état

> tout simplement de

> une partie de l'état

> [une propriété calculée](http://fr.vuejs.org/guide/computed.html)

2017-05-18 16:38 UTC, MachinisteWeb commented on docs/en/state.md
> +Lorsque `store.state.count` change, cela entraînera la ré-évaluation de la computed property, et déclenchera les actions DOM associées.
> propriété calculée

2017-05-18 16:38 UTC, Haeresis commented on docs/en/state.md
> +Cependant, ce pattern oblige le composant à compter sur le singleton global du store. Lorsqu'on utilise un système de module, il est nécessaire d'importer le store dans tous les composants qui utilis
> ce modèle oblige

> l'état du store

> de créer un jeu de test lorsque

2017-05-18 16:38 UTC, Haeresis commented on docs/en/state.md
> +Vuex fournit un méchanisme pour "injecter" le store dans tous les composants enfants du composant racine avec l'option `store` (activée par `Vue.use(Vuex)`) :
> « injecter »

2017-05-18 16:38 UTC, Haeresis commented on docs/en/state.md
> +  // fournit le store avec l'option "store".
> `store`

2017-05-18 16:38 UTC, Haeresis commented on docs/en/state.md
> +En fournissant l'option `store` à l'instance racine, le store sera injecté dans tous les composants enfants de la racine et sera disponible sur ceux-ci avec `this.$store`. Mettons à jours notre implé
> dans ceux-ci

2017-05-18 16:38 UTC, Haeresis commented on docs/en/state.md
> +Lorsqu'un composant a besoin d'utiliser plusieurs propriétés ou getters du state du store, déclarer toutes ces computed properties peut devenir répétitif et verbeux. Afin de palier à ça, nous pouvons
> plusieurs accesseurs ou propriétés de l'état du store

> propriété calculée

> des fonctions d'accès

2017-05-18 16:38 UTC, Haeresis commented on docs/en/state.md
> +// dans la version standalone, les helpers sont exposés comme Vuex.mapState
> dans la version complète

> `Vuex.mapState`

2017-05-18 16:38 UTC, Haeresis commented on docs/en/state.md
> +    // pour accéder au state local avec `this`, une fonction normale doit être utilisée
> à l'état

2017-05-18 16:38 UTC, Haeresis commented on docs/en/state.md
> +Il est également possible de fournir un tableau de chaînes de caractères à `mapState` lorsque le nom de la propriété du state du store est la même que celui du composant.
> de l'état

2017-05-18 16:38 UTC, Haeresis commented on docs/en/state.md
> +  // attacher this.count à store.state.count
> attacher `this.count` à `store.state.count`

2017-05-18 16:38 UTC, Haeresis commented on docs/en/state.md
>  ### Object Spread Operator
> Opérateur de décomposition

2017-05-18 16:38 UTC, Haeresis commented on docs/en/state.md
> +Notez que `mapState` renvoie un objet. Comment l'utiliser en complément des autres computed properties locales ? Normalement, il faudrait utiliser un outil pour fusionner les multiples objets en un s
> propriétés calculées

2017-05-18 16:38 UTC, Haeresis commented on docs/en/state.md
> +Notez que `mapState` renvoie un objet. Comment l'utiliser en complément des autres computed properties locales ? Normalement, il faudrait utiliser un outil pour fusionner les multiples objets en un s
> l'[opérateur de décomposition](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Op%C3%A9rateurs/Op%C3%A9rateur_de_d%C3%A9composition)

2017-05-18 16:38 UTC, Haeresis commented on docs/en/state.md
> +  // rajouter cet objet dans l'objet `computed` avec l'object spread operator
l'opérateur de décomposition

2017-05-18 16:38 UTC, Haeresis commented on docs/en/state.md
> +### Les composants peuvent toujours avoir un state local
> état local

2017-05-18 16:38 UTC, Haeresis commented on docs/en/state.md
> +Utiliser Vuex ne signifie pas que vous devez mettre **tout** votre state dans Vuex. Bien que le fait de mettre plus de state dans Vuex rende vos mutations de state plus explicites et plus debuggables
> votre état

> plus d'état dans Vuex

> mutation d'état

> debogable

> d'état appartient

> l'état local

> de vous adapter au mieux aux besoins de votre application.

2017-05-19 16:01 UTC, Haeresis commented
Merci @Kocal, il y a juste store qu'on va conserver tel quel étant donné qu'on a pris le parti de ne pas le traduire.

2017-05-19 16:26 UTC, Kocal approved these changes

2017-05-20 07:42 UTC, merged